# Generated by Django 5.1.1 on 2024-10-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorModel',
            new_name='Actor',
        ),
    ]
